server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "kaibot"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: true
    bufferDurationMs: 400
    playlistLoadLimit: 6
    playerUpdateInterval: 5
    youtubePlaylistLoadLimit: 6
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
metrics:
  prometheus:
    enabled: false
  cpu-cores: true
